Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 



In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
n=3

In [7]:
np.column_stack([arr**(n-1-i) for i in range(n)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [9]:
np.vander(arr,3)   # Test

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 


In [29]:
arr2= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=4

In [30]:
def moving_average(a, k) :
    ret = np.cumsum(a, dtype=float)
    ret[k:] = ret[k:] - ret[:-k]
    return ret[k - 1:] / k

In [33]:
moving_average(arr2,k)

array([  4.25,   5.5 ,   6.75,   7.75,  23.5 ,  39.5 ,  57.25,  79.25,
        88.  , 107.5 ])

In [34]:
print(f"No of input values :{len(arr2)} , No of Output values {len(arr2)-k+1}")

No of input values :13 , No of Output values 10
